name: Build Docs

on:
  workflow_call:
    secrets:
      JS:
        required: true

jobs:
  deploy-gh-pages:
    name: 发布文档
    runs-on: ubuntu-latest
    #if: ${{ secrets.JS }} == '4'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 安装 pnpm
        run: echo "发布文档成功"



