name: 输出github信息

on:
  push:
    branches:
      - main

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'

      - name: 根据提交信息来触发任务
        if: startsWith(github.event.head_commit.message, 'release') == false  
        id: message
        run: |
          echo ##########执行开始##########
          echo '${{ toJSON(github.event) }}'
          echo ##########执行成功结束##########

