name: 输出github信息

on:
  push:
    branches:
      - main

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: startout2
        id: github_context_message
        # head_commit  commits
        run: |
          echo ${{ github.event.commits.message }}    
          echo '${{ toJSON(github.event.head_commit.message) }}'      

