name: 输出github信息

on:
  push:
    branches:
      - main

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'

      - name: startout2
        id: github_context_head_commit_message
        # toJSON 输出有双引号
        run: echo ${{ toJSON(github.event.head_commit.message) }}
    
      - name: startout3
        if: startsWith(github.event.head_commit.message, 'outpp')
        id: message
        run: |
          echo ${{ github.event.head_commit.message }}
          echo github.event.head_commit.message

