name: Main Action

on:
  push:
    branches:
      - "**"
    tags:
      - v**
    paths-ignore:
      - img/**
      - docs/.vuepress/**/**.tsp
      - README.md
      - LICENSE
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/test')
    uses: ./.github/workflows/test.yml

  release:
    if: github.ref_name == 'main'
    name: Create Release
    uses: ./.github/workflows/release.yml

  merge:
    needs:
      - release
    name: Merge
    uses: ./.github/workflows/merge.yml

  docs:
    name: Deploy GitHub
    if: github.event_name == 'push' && github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
    needs:
      - release
      - merge
    uses: ./.github/workflows/docs.yml


























