name: Create Release

on:
  workflow_call:
    secrets:
      RELEASE_TOKEN:
        required: true
        
jobs:
  release-please:
    name: Create Release Changelog PR
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          release-type: node
