name: Test
on:
  push:
    tags:
      - test-**

jobs:
  test-demos:
    name: Test ${{ matrix.bundler }} on node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - "16"
          - "18"
          - "19" 
        bundler:
          - vite
         # - webpack
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: 设置Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: 打包项目
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm run build:${{ matrix.bundler }}
          > docs/.vuepress/dist/.nojekyll
          
      - name: 部署文档 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 
          repository-name: topjf/topjf.github.io
          # 部署的分支名称
          branch: page-${{ matrix.node }}
          folder: docs/.vuepress/dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true    
